name: Pytest Codecov
on: [push]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@master
      - name: Setup Python  
        uses: actions/setup-python@master
        with:
          python-version: '3.6'
      - name: Install Dependency
        run: |
          make install
      - name: Generate coverage report
        run: |
          poetry run pytest --cov=sjexample --cov-report=xml --cov-report=term
      - name: Upload coverage to Codecov  
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true